sudo: required

services:
  - docker

script:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make up composer-install test

after_success:
  - make coveralls
